version: "3.9"
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  api:
    build: ./apps/api
    env_file:
      - ./.env
      - ./apps/api/.env
    environment:
      DATABASE_URL: postgresql+psycopg://${POSTGRES_USER:-kaustya}:${POSTGRES_PASSWORD:-supersecret}@db:5432/${POSTGRES_DB:-kaustya_portfolio}
      ADMIN_API_KEY: ${ADMIN_API_KEY:-change-me}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:-http://localhost:5173}
    depends_on:
      - db
    ports:
      - "8000:8000"
volumes:
  db_data:
